sudo: required
services:
    - docker

before_install:
    - docker build -t bijaynayak870/docker-react -f Dockerfile.dev .

script:
    - docker run bijaynayak870/docker-react npm run test -- --coverage